- hosts: rustfs-arvan
  gather_facts: true
  become: true
  roles:
    - rustFS
  tags:
    - rustfs

- hosts: elasticsearch-arvan
  gather_facts: true
  become: true
  roles:
    - roles/elk/elasticsearch
  tags:
    - elasticsearch

- hosts: logstash-arvan
  gather_facts: true
  become: true
  roles:
    - roles/elk/logstash
  tags:
    - logstash

- hosts: kibana-arvan
  gather_facts: true
  become: true
  roles:
    - roles/elk/kibana
  tags:
    - kibana

- hosts: fleet-arvan
  gather_facts: true
  become: true
  roles:
    - roles/elk/fleet
  tags:
    - fleet

- hosts: agent-arvan
  gather_facts: true
  become: true
  roles:
    - roles/elk/agent
  tags:
    - agent