- hosts: rustfs-arvan
  gather_facts: true
  become: true
  roles:
    - rustFS
  tags:
    - rustfs

- hosts: influxdb-arvan
  gather_facts: true
  become: true
  roles:
    - observability/influxDB
  tags:
    - influxdb
    - observability

- hosts: telegraf-arvan
  gather_facts: true
  become: true
  roles:
    - observability/telegraf-docker
  tags:
    - telegraf-docker
    - observability

- hosts: gitlab-arvan
  gather_facts: true
  become: true
  roles:
    - gitlab/gitlab-omnibus
  tags:
    - gitlab
    - omnibus

- hosts: runner-arvan
  gather_facts: true
  become: true
  roles:
    - gitlab/gitlab-runner
  tags:
    - gitlab
    - runner

- hosts: jitsti-server
  gather_facts: true
  become: true
  roles:
    - jitsi
  tags:
    - jitsi
  
- hosts: confluence-server 
  gather_facts: true
  become: true
  roles:
    - confluence
  tags:
    - confluence

- name: Setup System Role
  hosts: alch-hp
  gather_facts: true
  become: true
  roles:
    - setup/system-setup
  tags:
    - system-setup