# preparation tasks

- name: Create Observability project directory 
  ansible.builtin.file:
    path: "{{ project_dir }}"
    state: directory
  tags:
    - project-dir

- name: Create InfluxDB service directory 
  ansible.builtin.file:
    path: "{{ service_dir }}"
    state: directory
  tags:
    - service-dir

- name: Create InfluxDB config directory 
  ansible.builtin.file:
    path: "{{ service_dir }}/configs"
    state: directory
    mode: '0755'
  tags:
    - config-dir