# Gitlab preparation tasks

- name: Creates service directory
  ansible.builtin.file:
    path: "{{ service_dir }}"
    state: directory
  tags:
    - service-dir

- name: Creates gitlab certs directory
  ansible.builtin.file:
    path: "{{ service_dir }}/certs"
    state: directory
    owner: root
    group: root
    mode: '0755'
  tags:
    - certs-dir 