---
project_dir: /opt/services
service_dir: "{{ project_dir }}/jitsi"
docker_networks:
  - prinet
  - pubnet

# .env vars
jitsi_version: stable-8960
jicofo_auth_password: YlhFJKEreDYmmZAZAwPkOlZmXcIFMsjjfelpf
jvb_auth_password: YlhFJKEreDYmmZAZAwPkOlZmXcIFMsjjjweifojefoijfo
jigasi_xmpp_password: JKEreDYmmZAZAwPvyufhjvtcdtgctyfjgftfkoklhj
jibri_recorder_password: JKEreDYmzwezaweesewssewsswswswswssffgyugyg
jibri_xmpp_password: YlhFJKEreDYmmXcIFMsjjjweifojefoijfoyfghyuguyg
config: /opt/services/jitsi/.jitsi-meet-cfg
http_port: 8000
https_port: 8443
tz: UTC
public_url: https://meet.mizbaninternal.ir
docker_host_address: 77.237.70.36
enable_lobby: 1
enable_prejoin_page: 1
enable_welcome_page: 1
enable_close_page: 1
disable_audio_levels: 0
enable_noisy_mic_detection: 1
enable_letsencrypt: 1
letsencrypt_domain: meet.example.com
letsencrypt_email: alice@atlanta.net
letsencrypt_use_staging: 1
etherpad_url_base: http://etherpad.meet.jitsi:9001
etherpad_public_url: https://etherpad.my.domain
etherpad_title: Video Chat
etherpad_default_pad_text: "Welcome to Web Chat!\\n\\n"
etherpad_skin_name: colibris
etherpad_skin_variants: super-light-toolbar super-light-editor light-background full-width-editor
jigasi_sip_uri: test@sip2sip.info
jigasi_sip_password: passw0rd
jigasi_sip_server: sip2sip.info
jigasi_sip_port: 5060
jigasi_sip_transport: UDP
enable_auth: 1
enable_guests: 0
auth_type: internal
jicofo_admins: admin@auth.meet.mizbaninternal.ir
prosody_admins: admin@auth.meet.mizbaninternal.ir
jwt_app_id: my_jitsi_app_id
jwt_app_secret: my_jitsi_app_secret
jwt_accepted_issuers: my_web_client,my_app_client
jwt_accepted_audiences: my_server1,my_server2
ldap_url: ldaps://ldap.domain.com/
ldap_base: DC=example,DC=domain,DC=com
ldap_binddn: CN=binduser,OU=users,DC=example,DC=domain,DC=com
ldap_bindpw: LdapUserPassw0rd
ldap_filter: (sAMAccountName=%u)
ldap_auth_method: bind
ldap_version: 3
ldap_use_tls: 1
ldap_tls_ciphers: SECURE256:SECURE128:!AES-128-CBC:!ARCFOUR-128:!CAMELLIA-128-CBC:!3DES-CBC:!CAMELLIA-128-CBC
ldap_tls_check_peer: 1
ldap_tls_cacert_file: /etc/ssl/certs/ca-certificates.crt
ldap_tls_cacert_dir: /etc/ssl/certs
ldap_start_tls: 1
xmpp_domain: meet.mizbaninternal.ir
xmpp_server: prosody
xmpp_bosh_url_base: http://prosody:5280
xmpp_auth_domain: auth.meet.mizbaninternal.ir
jvb_ws_domain: meet.mizbaninternal.ir
xmpp_muc_domain: muc.meet.mizbaninternal.ir
xmpp_internal_muc_domain: internal-muc.meet.mizbaninternal.ir
xmpp_guest_domain: guest.meet.mizbaninternal.ir
xmpp_cross_domain: "true"
xmpp_modules: ""
xmpp_muc_modules: muc_room_creation_restrict
muc_room_creation_allowed_jids: admin@auth.meet.mizbaninternal.ir
xmpp_internal_muc_modules: ""
jvb_brewery_muc: jvbbrewery
jvb_auth_user: jvb
jvb_stun_servers: meet-jit-si-turnrelay.jitsi.net:443
jvb_use_stun: "false"
jvb_stun_servers_active: ""
jvb_disable_stun: "true"
jvb_port: 10000
jvb_tcp_harvester_disabled: "true"
jvb_tcp_port: 4443
jvb_tcp_mapped_port: 4443
jvb_enable_apis: rest,colibri
jicofo_auth_user: focus
jicofo_reservation_rest_base_url: http://reservation.example.com
jicofo_enable_health_checks: "true"
jigasi_xmpp_user: jigasi
jigasi_brewery_muc: jigasibrewery
jigasi_port_min: 20000
jigasi_port_max: 20050
jigasi_enable_sdes_srtp: 1
jigasi_sip_keep_alive_method: OPTIONS
jigasi_health_check_sip_uri: keepalive
jigasi_health_check_interval: 300000
enable_transcriptions: 1
jigasi_transcriber_record_audio: "true"
jigasi_transcriber_send_txt: "true"
jigasi_transcriber_advertise_url: "true"
gc_project_id: ""
gc_private_key_id: ""
gc_private_key: ""
gc_client_email: ""
gc_client_id: ""
gc_client_cert_url: ""
enable_recording: 1
xmpp_recorder_domain: recorder.meet.mizbaninternal.ir
jibri_recorder_user: recorder
jibri_recording_dir: /config/recordings
jibri_finalize_recording_script_path: /config/finalize.sh
jibri_xmpp_user: jibri
jibri_brewery_muc: jibribrewery
jibri_pending_timeout: 90
jibri_strip_domain_jid: muc
jibri_logs_dir: /config/logs
disable_https: 1
enable_floc: 0
enable_http_redirect: 1
enable_hsts: 1
enable_ipv6: 0
restart_policy: unless-stopped
token_auth_url: https://auth.meet.example.com/{room}
