# agent preparation tasks

- name: Create elk project directory 
  ansible.builtin.file:
    path: "{{ project_dir }}"
    state: directory
  tags:
    - project-dir

- name: Create agent service directory 
  ansible.builtin.file:
    path: "{{ service_dir }}"
    state: directory
  tags:
    - aservice-dir

- name: Create agent data directory 
  ansible.builtin.file:
    path: "{{ service_dir }}/kdata"
    state: directory
    owner: '65532'
    group: '65532'
    mode: '0755'
    recurse: yes
  tags:
    - adata-dir