---

- name: Check if Docker CE and Compose Plugin are installed
  ansible.builtin.command: "{{ item }}"
  register: docker_install_check
  ignore_errors: true
  changed_when: false
  loop:
    - "docker --version"
    - "docker compose version"
  tags:
    - check-docker

- name: Fail if Docker CE is missing
  ansible.builtin.fail:
    msg: "CRITICAL: Docker (docker-ce) is not installed on this host. Please install it before running this playbook."
  when: docker_install_check.results[0].rc != 0
  tags:
    - check-docker

- name: Fail if Docker Compose is missing
  ansible.builtin.fail:
    msg: "CRITICAL: Docker Compose Plugin is missing. Run 'sudo apt install docker-compose-plugin' to fix."
  when: docker_install_check.results[1].rc != 0
  tags:
    - check-docker

- name: Success message of docker-check task
  ansible.builtin.debug:
    msg: "Environment check passed. Docker and Compose are ready!"
  tags:
    - check-docker

- name: Creates service directory 
  ansible.builtin.file:
    path: "{{ service_dir }}"
    state: directory
  tags:
    - preparing

- name: Copy the compose file with owner and permissions
  ansible.builtin.copy:
    src: compose.yml
    dest: "{{ service_dir }}/compose.yml"
  tags:
  - preparing

- name: Template the .env file to path
  ansible.builtin.template:
    src: .env.j2
    dest: "{{ service_dir }}/.env"
  tags:
  - preparing

- name: Template the heplify-server.toml file to path
  ansible.builtin.template:
    src: heplify-server.toml.j2
    dest: "{{ service_dir }}/heplify-server.toml"
  tags:
  - preparing

- name: Create docker external networks with name
  docker_network:
    name: "{{ item }}"
    driver_options:
      com.docker.network.bridge.name: "{{ item }}"
  loop: "{{ docker_networks }}"
  tags:
    - docker-networks

- name: Pull Traefik image for project
  community.docker.docker_compose_v2_pull:
    project_src: "{{ service_dir }}"
    policy: missing #pull if only the images doesn't exist locally
  tags:
    - pull

- name: Deploy Traefik Docker Compose
  community.docker.docker_compose_v2:
    project_src: "{{ service_dir }}"
  tags:
    - deploy