#SPDX-License-Identifier: MIT-0
---
# tasks file for homer

- name: Deploy homer server
  include_tasks: heplify-server.yml
  tags:
    - homer
    - server
    
- name: Deploy homer agent
  include_tasks: heplify-agent.yml
  tags:
    - homer
    - agent
