networks:
  prinet:
    external: true
    name: ${PRIVATE_NETWORK}
  pubnet:
    external: true
    name: ${PUBLIC_NETWORK}

services:
  logstash:
    image: dhi.io/logstash:${LOGSTASH_IMAGE_TAG}
    container_name: ${LOGSTASH_CONTAINER_NAME}
    restart: ${RESTART_POLICY}
    volumes:
      - ./pipeline:/usr/share/logstash/pipeline:ro
      - ./ldata:/usr/share/logstash/data
    ports:
      - "127.0.0.1:5044:5044"
      - "127.0.0.1:9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx${MINIMUM_HEAP_SIZE} -Xms${MINIMUM_HEAP_SIZE}"
      NODE_NAME: ${LOGSTASH_NODE_NAME}
      HTTP_HOST: ${LOGSTASH_HTTP_HOST}
      PIPELINE_WORKERS: ${LOGSTASH_PIPELINE_WORKERS}
      PIPELINE_BATCH_SIZE: ${LOGSTASH_PIPELINE_BATCH_SIZE}
      QUEUE_TYPE: "${LOGSTASH_QUEUE_TYPE}"
      MONITORING_ENABLED: "${LOGSTASH_MONITORING_ENABLED}"
      MONITORING_ELASTICSEARCH_HOSTS: "${ELASTIC_HOSTNAME}"
      MONITORING_ELASTICSEARCH_USERNAME: "${ELASTIC_USERNAME}"
      MONITORING_ELASTICSEARCH_PASSWORD: "${ELASTIC_PASSWORD}"
      ELASTIC_HOSTS: "${ELASTIC_HOSTNAME}"
      ELASTIC_USER: "${ELASTIC_USERNAME}"
      ELASTIC_PASS: "${ELASTIC_PASSWORD}"
    networks:
      - prinet
      - pubnet
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=pubnet"
      - "traefik.tcp.routers.logstash-beats.rule=Host(`${LOGSTASH_SUBDOMAIN}.${MAIN_DOMAIN}`)"
      - "traefik.tcp.routers.logstash-beats.entrypoints=beats"
      - "traefik.tcp.services.logstash-beats.loadbalancer.server.port=5044"
      - "traefik.http.routers.logstash-api.rule=Host(`${LOGSTASH_SUBDOMAIN}.${MAIN_DOMAIN}`)"
      - "traefik.http.routers.logstash-api.entrypoints=https"
      - "traefik.http.routers.logstash-api.tls=true"
      - "traefik.http.routers.logstash-api.tls.certresolver=le"
      - "traefik.http.services.logstash-api.loadbalancer.server.port=9600"