#SPDX-License-Identifier: MIT-0
---
# defaults file for postgres-master

# global
project_dir: /opt/services
service_dir: "{{ project_dir }}/postgres-master"
docker_networks:
  - prinet
  - pubnet

postgres_replication_user: postgresreplication
postgres_replication_password: postgresreplication

# docker vars
restart_policy: unless-stopped

postgres_version: 16
postgres_master_hostname: postgres-master
postgres_master_container_name: postgres-master
postgres_master_user: postgresuser
postgres_master_password: postgrespass
postgres_master_db: postgres
postgres_master_port: 5432

postgres_exporter_tag: v0.17.1
postgres_exporter_hostname: postgres-exporter
postgres_exporter_container_name: postgres-exporter
postgres_exporter_user: exporteruser
postgres_exporter_password: exporterpass
extend_collectors: "database,table,functions,indexes,roles,locks,settings,activity,stat_user_tables,stat_user_indexes,statio_user_tables,statio_user_indexes"
disable_collectors: "wal"
postgres_exporter_port: 9187

# Postgres Configs
primary_ip: 127.0.0.1
standby_ip: 127.0.0.1
app_network: 10.0.0.0/24
replication_slot: standby1
wal_keep_size: 2048MB
max_wal_senders: 10
max_replication_slots: 10
enable_ssl: false
enable_archive: true
wal_archive_dir: /var/lib/postgresql/wal_archive

max_worker_processes: 8
max_parallel_workers_per_gather: 2
max_parallel_workers: 4
max_parallel_maintenance_workers: 2
shared_buffers: 1024MB
effective_cache_size: 3072MB
work_mem: 32MB
