#SPDX-License-Identifier: MIT-0
---
# defaults file for postgres-master

# global
project_dir: /opt/services
service_dir: "{{ project_dir }}/postgres-master"
docker_networks:
  - prinet
  - pubnet

# docker vars
restart_policy: unless-stopped
servr_ip: 127.0.0.1

postgres_version: 16
postgres_master_hostname: postgres-master
postgres_master_container_name: postgres-master
postgres_master_user: postgres
postgres_master_password: postgres
postgres_master_db: postgres
postgres_master_port: 5432

postgres_exporter_tag: v0.17.1
postgres_exporter_hostname: postgres-exporter
postgres_exporter_container_name: postgres-exporter
postgres_exporter_user: exporter
postgres_exporter_password: exporter
extend_collectors: "database,table,functions,indexes,roles,locks,settings,activity,stat_user_tables,stat_user_indexes,statio_user_tables,statio_user_indexes"
disable_collectors: "wal"
postgres_exporter_port: 9187