#SPDX-License-Identifier: MIT-0
---
# defaults file for agent

# global
project_dir: /opt/services/elk
service_dir: "{{ project_dir }}/kibana"
docker_networks:
  - prinet
  - pubnet

# .env vars
agent_image_tag: 8.19.11
restart_policy: unless-stopped
agent_container_name: elastic-agent
fleet_subdomain: a
main_domain: elk.com
enrollment_token: token