networks:
  prinet:
    name: ${PRIVATE_NETWORK}
    external: true
  pubnet:
    name: ${PUBLIC_NETWORK}
    external: true

services:
  # RustFS main service
  rustfs:
    security_opt:
      - "no-new-privileges:true"
    image: rustfs/rustfs:${RUSTFS_IMAGE_TAG}
    user: "10001:10001"
    container_name: ${RUSTFS_CONTAINER_NAME}
    ports:
      - "127.0.0.1:9000:9000" # S3 API port
      - "127.0.0.1:9001:9001" # Console port
    environment:
      - RUSTFS_VOLUMES=/data/rustfs
      - RUSTFS_ADDRESS=0.0.0.0:9000
      - RUSTFS_CONSOLE_ADDRESS=0.0.0.0:9001
      - RUSTFS_CONSOLE_ENABLE=true
      - RUSTFS_CORS_ALLOWED_ORIGINS=*
      - RUSTFS_CONSOLE_CORS_ALLOWED_ORIGINS=*
      - RUSTFS_ACCESS_KEY=${RUSTFS_ACCESS_KEY}
      - RUSTFS_SECRET_KEY=${RUSTFS_SECRET_KEY}
      - RUSTFS_OBS_LOGGER_LEVEL=info
      - RUSTFS_OBS_ENDPOINT=http://${OTEL_CONTAINER_NAME}:4318
      - RUSTFS_CORS_ALLOWED_ORIGINS=https://${CONSOLE_DOMAIN},https://${S3_DOMAIN}
      - RUSTFS_CONSOLE_CORS_ALLOWED_ORIGINS=https://${CONSOLE_DOMAIN},https://${S3_DOMAIN}
    volumes:
      - ./data:/data/rustfs
      - ./logs:/logs
    networks:
      - ${PRIVATE_NETWORK}
    restart: ${RESTART_POLICY}
    healthcheck:
      test:
        [
          "CMD",
          "sh", "-c",
          "curl -f http://127.0.0.1:9000/health && curl -f http://127.0.0.1:9001/rustfs/console/health"
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      otel-collector:
        condition: service_started
        required: false

  # OpenTelemetry Collector
  otel-collector:
    image: otel/opentelemetry-collector-contrib:${OTEL_IMAGE_TAG}
    container_name: ${OTEL_CONTAINER_NAME}
    command:
      - --config=/etc/otelcol-contrib/otel-collector.yml
    volumes:
      - ./otel-confs/otel-collector-config.yml:/etc/otelcol-contrib/otel-collector.yml:ro
    ports:
      - "127.0.0.1:4317:4317" # OTLP gRPC receiver
      - "127.0.0.1:4318:4318" # OTLP HTTP receiver
      - "127.0.0.1:8888:8888" # Prometheus metrics
      - "127.0.0.1:8889:8889" # Prometheus exporter metrics
    networks:
      - ${PRIVATE_NETWORK}
    restart: ${RESTART_POLICY}

  nginx:
    image: nginx:${NGINX_IMAGE_TAG}
    container_name: ${NGINX_CONTAINER_NAME}
    ports:
      - "80:80"    # HTTP
      - "443:443"  # HTTPS
    volumes:
      - ./nginx/conf.d/nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
      - ./nginx/certbot-webroot:/var/www/certbot:ro
    networks:
      - ${PRIVATE_NETWORK}
      - ${PUBLIC_NETWORK}
    depends_on:
      - rustfs