#SPDX-License-Identifier: MIT-0
---
# defaults file for gitlab-omnibus

service_dir: "{{ project_dir }}/gitlab"
backups_dir: "{{ service_dir }}/backup"
project_dir: /opt/services
docker_network:
  - pubnet
  - prinet

# .env variables
restart_policy: unless-stopped
gitlab_image_tag: 18.6.1-ce.0
gitlab_container_name: gitlab-omnibus
main_domain: domain.com
gitlab_main_domain: "gitlab.{{ main_domain }}"
gitlab_root_password: strongrootpassforgitlab
gitlab_nginx_max_body_size: 10240m
smtp_address: smtp.gmail.com
smtp_port: 587
smtp_username: smtp@gmail.com
smtp_password: smtpstrongpass
smtp_domain: smtp.gmail.com
gitlab_backup_keep_time: 604800
gitlab_s3_access_key: kfjwlefjwefjwefw
gitlab_s3_secret_key: efkweo;fkwefo;ewjfowe;jfweof
gitlab_s3_endpoint: s3.domain.com
gitlab_s3_bucket: gitlab-backup
gitlab_registry_domain: "reg.{{ gitlab_main_domain }}"
gitlab_reg_max_body_size: 20480m
gitlab_registery_s3_bucket: gitlab-registery

# backup script variables
gitlab_backup_encryption_pass:
s3_api_endpoint:
s3_gitlab_backup_username:
s3_gitlab_backup_password:
s3_gitlab_backup_config_bucket:
